# config.yaml

# Dataset configuration
dataset:
  type: x3d
  root_dir: ./X3D_Videos
  batch_size: 32

# Model configuration
model:
  type: stead
  feature_dim: 2048
  hidden_dim: 64
  seq_len: 16
  num_heads: 4

# Training configuration
training:
  epochs: 10
  learning_rate: 1e-3